name= input ('Enter you name:')
age= input ('Enter you age:')
location= input ('Enter where you live:')
print ( 'Hello' ,name,'you are ' ,age ,'years old and you live in ',location,)
print ('Have a wonderful week' ,name,)
